# Generated by Django 2.2.20 on 2021-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(default='', max_length=70)),
                ('tipoComprobante', models.CharField(default='', max_length=200)),
                ('total', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
