# Generated by Django 2.2.20 on 2021-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturaxion', '0002_auto_20210604_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='conceptoDescripcion',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='factura',
            name='conceptoImporte',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='conceptoValor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisorNombre',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisorRFC',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuestosTotalImp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuestosTransImporte',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuestosTransTasa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='receptorNombre',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='factura',
            name='receptorRFC',
            field=models.CharField(default='', max_length=13),
        ),
    ]
